# Theme metadata
name = "custom"

# Is theme light or dark?
[light]

# Primary
primary = "#990000"
primary_light = "#990000"
primary_dark = "#f7f7f7"

# Menu
menu_primary = "#f7f7f7"
menu_text = "#000000"
menu_text_active = "#000000"
menu_title = "#990000"

# Backgrounds
background = "#fff"
home_section_odd = "#fff"
home_section_even = "#f7f7f7"